### ISSUE TITLE
undefined reference to `dgetri_'

### ISSUE THREAD

**Issue by dataPulverizer** [kaleidicassociates/lubeck#1]
Tried building a test package with lubeck and mir-algorithm specifically trying to call inv function. Get the following error:

.dub/packages/mir-lapack-0.0.3/mir-lapack/source/mir/lapack.d:53: undefined reference to `dgetri_'

In the dub.json I include:

"dependencies": {"lubeck": "~>0.0.3", "mir-algorithm": "~>0.6.6"}

**Comment by 9il** [comment]
It is not a bug) It is a features! You are able to link a lapack library you want. Please [the example](https://github.com/kaleidicassociates/lubeck/blob/master/example/dub.sdl).

**Comment by dataPulverizer** [comment]
Thanks

**Comment by Marenz** [comment]
It sounds like this is optional.. but how can you _not_ link with it then? I couldn't see any flags to define that would make the library not use those functions?
