### ISSUE TITLE
Newest release doesn't compile anymore on Buildkite

### ISSUE THREAD

**Issue by wilzbach** [kaleidicassociates/lubeck#21]
https://buildkite.com/dlang/dmd/builds/3946#3311f4b4-ae52-4df5-8388-6315ccc1db18

```
Unresolvable dependencies to package mir-algorithm:
  | mir-blas 1.1.4 depends on mir-algorithm >=2.0.0-beta2 <4.0.0
  | mir-random 2.2.0 depends on mir-algorithm ~>3.2.1
  | mir-random 2.2.0 depends on mir-algorithm ~>3.2.1 (optional)
  | Unresolvable dependencies to package mir-algorithm:
  | mir-blas 1.1.4 depends on mir-algorithm >=2.0.0-beta2 <4.0.0
  | mir-random 2.2.0 depends on mir-algorithm ~>3.2.1
  | mir-random 2.2.0 depends on mir-algorithm ~>3.2.1 (optional)

```

Just a dependency problem, but as this seems to happen quite frequently it would be great if we could either change the Buildkite code to use the same testing as here or add the same testing here.

**Comment by wilzbach** [comment]
> Just a dependency problem, but as this seems to happen quite frequently it would be great if we could either change the Buildkite code to use the same testing as here or add the same testing here.

Well, Travis is failing here too:

https://www.travis-ci.org/kaleidicassociates/lubeck

**Comment by 9il** [comment]
should work now, mir-random v2.2.1 has been released
