### ISSUE TITLE
Seems there is a dub conflict with this package.

### ISSUE THREAD

**Issue by schveiguy** [kaleidicassociates/lubeck#28]
See for instance:

https://buildkite.com/dlang/druntime/builds/3254#175779b7-d453-438c-98f0-350a1ad3889e/115

**Comment by 9il** [comment]
Obviously, it is a dub bug. I got a set of similar bug reports each month.

**Comment by 9il** [comment]
The bug should be fixed. If rerunning the build wouldn't help, please reopen the issue.
